## 머신러닝 기초

In [2]:
import torch

x = torch.tensor(2.0, requires_grad=True)
y = x ** 2
y.backward()
print(x.grad)

tensor(4.)


In [3]:
import numpy as np

tsor = np.arange(7.0)
tsor.ndim # 1.    # 텐서의 차원
tsor.shape # (7,)  # 텐서의 크기



(7,)

In [4]:
tsor2 = np.arange(1.0, 13).reshape((4,3))
tsor2.ndim #2
tsor2.shape # (4,3)


(4, 3)

In [2]:
import torch

tsor3 = torch.arange(0.0, 7)
tsor3.dim() # 1
tsor3.shape  # torch.Size([7])
tsor3.size() # torch.Size([7])
tsor3.shape[0]

7

In [ ]:
t = torch.arange(1,13.0).reshape((4,3))
t.dim() #2
t.size() # torch.Size([4, 3])
t.shape # torch.Size([4, 3])

t[:,1]
t[:,1].size()
t[:,:-1] # 마지막 차원 제외


tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])

In [ ]:
m1 = torch.FloatTensor([3,3])
m2 = torch.FloatTensor([2,2])
m1 + m2 # tensor([5., 5.])

tensor([5., 5.])

In [ ]:
m1 = torch.FloatTensor([1,2])
m2 = torch.FloatTensor([3])
m1 + m2 # tensor([4., 5.]) 큰 size에 맞춰서 작은 사이즈가 중복되어 생김

tensor([4., 5.])

In [ ]:
m1 = torch.FloatTensor([[1,2],[3,4]]) # 2*2
m2 = torch.FloatTensor([[1],[2]]) # 2*1
m1 + m2 # tensor([[2., 3.],
        #         [5., 6.]])

tensor([[2., 3.],
        [5., 6.]])

In [30]:
m1 = torch.FloatTensor([[1,2],[3,4]]) # 2*2
m2 = torch.FloatTensor([[1],[2]]) # 2*1

m1.matmul(m2).shape # torch.Size([2, 1]) 내적 (dot 연산) -> matrix multiplication 
(m1 @ m2).shape # 위와 같은 연산
torch.matmul(m1,m2)
# torch.dot(m1,m2) 벡터끼리의 내적만 지원함 행렬곱은 안됨 -> 1D 전용

tensor([[ 5.],
        [11.]])

#### 평균

In [ ]:
t = torch.FloatTensor([1,2])
t.mean() # tensor(1.5000)
m1 = torch.FloatTensor([[1,2],[3,4]]) # 2*2
m1.mean()

m1.mean(dim=0 ,dtype=torch.float) # tensor([2., 3.])
m1.mean(dim=1 ,dtype=torch.float) # tensor([1.5000, 3.5000])
# m1.mean(dim=2 ,dtype=torch.float) # Dimension out of range (expected to be in range of [-2, 1], but got 2)

# dim=0이면 0번째 축(행 방향) 을 없애면서 계산,
# dim=1이면 1번째 축(열 방향) 을 없애면서 계산
m1.mean(dim=-1 ,dtype=torch.float) # tensor([1.5000, 3.5000])


tensor([1.5000, 3.5000])

#### 덧셈


In [ ]:
t2 = torch.FloatTensor([[1,2],[3,4]])
t2.sum() #tensor(10.)
t2.sum(dim=0) # tensor([4., 6.])
t2.sum(dim=1) # tensor([3., 7.])
t2.sum(dim=-1) # tensor([3., 7.])

tensor([3., 7.])

#### max, arxmax


In [ ]:
t3 = torch.FloatTensor([[1,2],[3,4]])
t3.max() # tensor(4.)
t3.max(dim=0) # torch.return_types.max(values=tensor([3., 4.]),indices=tensor([1, 1])) # indice= 최대값위치
t3.max(dim=1) # torch.return_types.max(values=tensor([2., 4.]),(indices=tensor([1, 1]))

t3.max(dim=0)[0] # tensor([3., 4.]) -> tensor
t3.max(dim=0)[1] # tensor([1, 1]) -> indice

tensor([1, 1])

#### view - 원소의 수를 유지하며 텐서 크기 변경 (np.reshape())

In [ ]:
import numpy as np
tt = np.arange(0,12).reshape((4,3))
tt

ft = torch.FloatTensor(tt)

# tensor([[ 0.,  1.,  2.],
#         [ 3.,  4.,  5.],
#         [ 6.,  7.,  8.],
#         [ 9., 10., 11.]])


ft.shape # torch.Size([4, 3])
ft

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [71]:
ft.view([-1,2])

tensor([[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]])

In [74]:
ft.view([-1,1,3]).shape # torch.Size([4, 1, 3])

torch.Size([4, 1, 3])

#### squeeze -1 차원 제거, unsqueeze +1 차원추가

In [ ]:
ttt = ttt = torch.arange(1,4).reshape((3,1))

ttt.shape #torch.Size([3, 1])
ttt.squeeze().shape # torch.Size([3])


tttt = torch.arange(1,4).reshape((3,1))
# tensor([[1],
#         [2],
#         [3]])
# torch.Size([3, 1])

tttt.unsqueeze(0) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.

# tensor([[[1],
#          [2],
#          [3]]])
# torch.Size([1, 3, 1])

tttt.unsqueeze(1)

# tensor([[[1]],

#         [[2]],

        # [[3]]])
tttt.unsqueeze(1).shape

#torch.Size([3, 1, 1])



torch.Size([3, 1])

In [95]:
tttt.unsqueeze(-1).shape # torch.Size([3, 1, 1])

tttt.view(1,-1) # torch.Size([1, 3])

tensor([[1, 2, 3]])

#### 타입캐스팅

In [ ]:
ft = torch.LongTensor([1,2,3,4]) #tensor([1, 2, 3, 4])
ft.float() # tensor([1., 2., 3., 4.])

bt = torch.ByteTensor([True, False, False, True]) # tensor([1, 0, 0, 1], dtype=torch.uint8)
bt.long() # tensor([1, 0, 0, 1])
bt.float() # tensor([1., 0., 0., 1.])

tensor([1., 0., 0., 1.])

#### tensor 연산

In [ ]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

torch.cat((x,y)) #

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])