## 머신러닝 기초

In [2]:
import torch

x = torch.tensor(2.0, requires_grad=True)
y = x ** 2
y.backward()
print(x.grad)

tensor(4.)


In [3]:
import numpy as np

tsor = np.arange(7.0)
tsor.ndim # 1.    # 텐서의 차원
tsor.shape # (7,)  # 텐서의 크기



(7,)

In [4]:
tsor2 = np.arange(1.0, 13).reshape((4,3))
tsor2.ndim #2
tsor2.shape # (4,3)


(4, 3)

In [2]:
import torch

tsor3 = torch.arange(0.0, 7)
tsor3.dim() # 1
tsor3.shape  # torch.Size([7])
tsor3.size() # torch.Size([7])
tsor3.shape[0]

7

In [ ]:
t = torch.arange(1,13.0).reshape((4,3))
t.dim() #2
t.size() # torch.Size([4, 3])
t.shape # torch.Size([4, 3])

t[:,1]
t[:,1].size()
t[:,:-1] # 마지막 차원 제외


tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])

In [ ]:
m1 = torch.FloatTensor([3,3])
m2 = torch.FloatTensor([2,2])
m1 + m2 # tensor([5., 5.])

tensor([5., 5.])

In [ ]:
m1 = torch.FloatTensor([1,2])
m2 = torch.FloatTensor([3])
m1 + m2 # tensor([4., 5.]) 큰 size에 맞춰서 작은 사이즈가 중복되어 생김

tensor([4., 5.])

In [ ]:
m1 = torch.FloatTensor([[1,2],[3,4]]) # 2*2
m2 = torch.FloatTensor([[1],[2]]) # 2*1
m1 + m2 # tensor([[2., 3.],
        #         [5., 6.]])

tensor([[2., 3.],
        [5., 6.]])

In [30]:
m1 = torch.FloatTensor([[1,2],[3,4]]) # 2*2
m2 = torch.FloatTensor([[1],[2]]) # 2*1

m1.matmul(m2).shape # torch.Size([2, 1]) 내적 (dot 연산) -> matrix multiplication 
(m1 @ m2).shape # 위와 같은 연산
torch.matmul(m1,m2)
# torch.dot(m1,m2) 벡터끼리의 내적만 지원함 행렬곱은 안됨 -> 1D 전용

tensor([[ 5.],
        [11.]])

#### 평균

In [ ]:
t = torch.FloatTensor([1,2])
t.mean() # tensor(1.5000)
m1 = torch.FloatTensor([[1,2],[3,4]]) # 2*2
m1.mean()

m1.mean(dim=0 ,dtype=torch.float) # tensor([2., 3.])
m1.mean(dim=1 ,dtype=torch.float) # tensor([1.5000, 3.5000])
# m1.mean(dim=2 ,dtype=torch.float) # Dimension out of range (expected to be in range of [-2, 1], but got 2)

# dim=0이면 0번째 축(행 방향) 을 없애면서 계산,
# dim=1이면 1번째 축(열 방향) 을 없애면서 계산
m1.mean(dim=-1 ,dtype=torch.float) # tensor([1.5000, 3.5000])


tensor([1.5000, 3.5000])

#### 덧셈


In [ ]:
t2 = torch.FloatTensor([[1,2],[3,4]])
t2.sum() #tensor(10.)
t2.sum(dim=0) # tensor([4., 6.])
t2.sum(dim=1) # tensor([3., 7.])
t2.sum(dim=-1) # tensor([3., 7.])

tensor([3., 7.])

#### max, arxmax


In [ ]:
t3 = torch.FloatTensor([[1,2],[3,4]])
t3.max() # tensor(4.)
t3.max(dim=0) # torch.return_types.max(values=tensor([3., 4.]),indices=tensor([1, 1])) # indice= 최대값위치
t3.max(dim=1) # torch.return_types.max(values=tensor([2., 4.]),(indices=tensor([1, 1]))

t3.max(dim=0)[0] # tensor([3., 4.]) -> tensor
t3.max(dim=0)[1] # tensor([1, 1]) -> indice

tensor([1, 1])

#### view - 원소의 수를 유지하며 텐서 크기 변경 (np.reshape())

In [ ]:
import numpy as np
tt = np.arange(0,12).reshape((4,3))
tt

ft = torch.FloatTensor(tt)

# tensor([[ 0.,  1.,  2.],
#         [ 3.,  4.,  5.],
#         [ 6.,  7.,  8.],
#         [ 9., 10., 11.]])


ft.shape # torch.Size([4, 3])
ft

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [71]:
ft.view([-1,2])

tensor([[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]])

In [74]:
ft.view([-1,1,3]).shape # torch.Size([4, 1, 3])

torch.Size([4, 1, 3])

#### squeeze -1 차원 제거, unsqueeze +1 차원추가

In [ ]:
ttt = ttt = torch.arange(1,4).reshape((3,1))

ttt.shape #torch.Size([3, 1])
ttt.squeeze().shape # torch.Size([3])


tttt = torch.arange(1,4).reshape((3,1))
# tensor([[1],
#         [2],
#         [3]])
# torch.Size([3, 1])

tttt.unsqueeze(0) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.

# tensor([[[1],
#          [2],
#          [3]]])
# torch.Size([1, 3, 1])

tttt.unsqueeze(1)

# tensor([[[1]],

#         [[2]],

        # [[3]]])
tttt.unsqueeze(1).shape

#torch.Size([3, 1, 1])



torch.Size([3, 1])

In [95]:
tttt.unsqueeze(-1).shape # torch.Size([3, 1, 1])

tttt.view(1,-1) # torch.Size([1, 3])

tensor([[1, 2, 3]])

#### 타입캐스팅

In [ ]:
ft = torch.LongTensor([1,2,3,4]) #tensor([1, 2, 3, 4])
ft.float() # tensor([1., 2., 3., 4.])

bt = torch.ByteTensor([True, False, False, True]) # tensor([1, 0, 0, 1], dtype=torch.uint8)
bt.long() # tensor([1, 0, 0, 1])
bt.float() # tensor([1., 0., 0., 1.])

tensor([1., 0., 0., 1.])

#### tensor 연산

In [ ]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

torch.cat((x,y)) # dim= 0 

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [107]:
torch.cat((x,y),dim=1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

#### 스태킹

In [ ]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

torch.stack((x,y,z)) #1+1+1 차원 -> 2차원


tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [ ]:
torch.cat((x.unsqueeze(0),y.unsqueeze(0), z.unsqueeze(0))) # 위와 같다.

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

#### one_like, zeros_like -0, 1로 채워진 텐서

In [112]:
o = torch.FloatTensor([[0,1,2],[2,1,0]]) # 2 * 3 텐서
torch.ones_like(o)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [113]:
torch.zeros_like(o)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

#### in place operation 연산

In [ ]:
x = torch.FloatTensor([[1,2],[3,4]])
x.mul(2)
x # 원본은 그대로임
x.mul_(2)
x # 원본이 변경됨( in_place version)

tensor([[2., 4.],
        [6., 8.]])

## 선형회귀와 다중미분

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

x_train = torch.FloatTensor([[1],[2],[3]]) # 3*1
y_train = torch.FloatTensor([[2],[4],[6]]) # 3*1

x_train.shape # torch.Size([3, 1])

# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시

W = torch.zeros(1, requires_grad=True) # tensor([0.], requires_grad=True)
W3 = torch.zeros(0, requires_grad=True) # tensor([], requires_grad=True)
W2 = torch.zeros((3,3), requires_grad=True) 

# tensor([[0., 0., 0.],
#         [0., 0., 0.],
#         [0., 0., 0.]], requires_grad=True)

b = torch.zeros(1, requires_grad=True)

# 경사하강법 적용할 optimizer 함수 SGD를 정의

optimizer = optim.SGD([W,b],lr=0.01) # SGD - Stochastic Gradient Descent

hypothesis = x_train * W + b

# tensor([[0.],
#         [0.],
#         [0.]], grad_fn=<AddBackward0>)

# 비용함수 = average(가설값 - 실제데이터)^2

cost = torch.mean((hypothesis - y_train) ** 2)
# tensor(18.6667, grad_fn=<MeanBackward0>)

# gradient 0으로 초기화

optimizer.zero_grad()

# 비용함수를 미분하여 gradient 계산

cost.backward()

# W, b 를 업데이트

optimizer.step()



In [133]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

x_train = torch.FloatTensor([[1],[2],[3]]) # 3*1
y_train = torch.FloatTensor([[2],[4],[6]]) # 3*1

x_train.shape # torch.Size([3, 1])

# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시

W = torch.zeros(1, requires_grad=True) # tensor([0.], requires_grad=True)


# tensor([[0., 0., 0.],
#         [0., 0., 0.],
#         [0., 0., 0.]], requires_grad=True)

b = torch.zeros(1, requires_grad=True)

# 경사하강법 적용할 optimizer 함수 SGD를 정의

optimizer = optim.SGD([W,b],lr=0.01) # SGD - Stochastic Gradient Descent

nb_epochs = 2000 # 원하는 만큼 경사하강법을 반복

for epoch in range(nb_epochs +1) :
    
    hypothesis = x_train * W + b
    cost = torch.mean((hypothesis - y_train) ** 2)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

#   100번 마다 로그 출력
    if epoch % 100 == 0 :
      print("Epoch {:4d}/{} W: {:3f}, b: {:.3f}, Cost: {:6f}".format(epoch, nb_epochs, W.item(), b.item(), cost.item()))

Epoch    0/2000 W: 0.186667, b: 0.080, Cost: 18.666666
Epoch  100/2000 W: 1.745691, b: 0.578, Cost: 0.048171
Epoch  200/2000 W: 1.800099, b: 0.454, Cost: 0.029767
Epoch  300/2000 W: 1.842860, b: 0.357, Cost: 0.018394
Epoch  400/2000 W: 1.876473, b: 0.281, Cost: 0.011366
Epoch  500/2000 W: 1.902897, b: 0.221, Cost: 0.007024
Epoch  600/2000 W: 1.923668, b: 0.174, Cost: 0.004340
Epoch  700/2000 W: 1.939996, b: 0.136, Cost: 0.002682
Epoch  800/2000 W: 1.952832, b: 0.107, Cost: 0.001657
Epoch  900/2000 W: 1.962921, b: 0.084, Cost: 0.001024
Epoch 1000/2000 W: 1.970853, b: 0.066, Cost: 0.000633
Epoch 1100/2000 W: 1.977087, b: 0.052, Cost: 0.000391
Epoch 1200/2000 W: 1.981989, b: 0.041, Cost: 0.000242
Epoch 1300/2000 W: 1.985842, b: 0.032, Cost: 0.000149
Epoch 1400/2000 W: 1.988870, b: 0.025, Cost: 0.000092
Epoch 1500/2000 W: 1.991251, b: 0.020, Cost: 0.000057
Epoch 1600/2000 W: 1.993122, b: 0.016, Cost: 0.000035
Epoch 1700/2000 W: 1.994594, b: 0.012, Cost: 0.000022
Epoch 1800/2000 W: 1.995750

In [134]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)
# 훈련 데이터
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])
# 가중치 w와 편향 b 초기화
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD( [ w1, w2, w3, b] , lr=0.00001 )


nb_epochs = 1000
for epoch in range(nb_epochs + 1):
# H(x) 계산
  hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b
# cost 계산
  cost = torch.mean((hypothesis - y_train) ** 2)
# cost로 H(x) 개선
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
# 100번마다 로그 출력
  if epoch % 100 == 0:
    print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost:{:.6f}'.format(

  epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(),cost.item()
))

Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost:29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost:1.563628
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost:1.497595
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost:1.435044
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost:1.375726
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost:1.319507
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost:1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost:1.215703
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost:1.167810
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost:1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost:1.079390


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)
x_train = torch.FloatTensor([[73, 80, 75],
[93, 88, 93],
[89, 91, 80],
[96, 98, 100],
[73, 66, 70]])

y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])
# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)
nb_epochs = 20
for epoch in range(nb_epochs + 1):
# H(x) 계산, 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
  hypothesis = x_train.matmul(W) + b
  
  # cost 계산
  cost = torch.mean((hypothesis - y_train) ** 2)
  # cost로 H(x) 개선
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()


print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
))
# 학습하여 산출된 가중치( W1~3 과 b값) 에 대하여 임의의 입력 값 적용
# no_grad() block 내 모든 연산수행시 역전파(기울기 계산) 비활성화
#
with torch.no_grad():
# 예측하고 싶은 임의의 입력값
  new_input = torch.FloatTensor([[75, 85, 72]])
  prediction = new_input.matmul(W) + b
  
print('Predicted value for input {}: {}'.format(new_input.squeeze().tolist(),prediction.item()))




PyTorch는 기본적으로 모든 Tensor 연산을 추적(trace) 합니다.
왜냐하면 backward()로 역전파(gradient 계산)를 하기 위해서죠.

하지만 예측할 때는 더 이상 학습하지 않으므로,
기울기를 계산할 필요가 없습니다 → 메모리 절약 + 속도 향상.

with torch.no_grad():
    prediction = model(x)

In [ ]:
class Hello:
    def __enter__(self):
        # 사용할 자원을 가져오거나 만든다(핸들러 등)
        print('enter...')
        return self # 반환값이 있어야 VARIABLE를 블록내에서 사용할 수 있다
        
    def sayHello(self, name):
        # 자원을 사용한다. ex) 인사한다
        print('hello ' + name)

    def __exit__(self, exc_type, exc_val, exc_tb):
        # 마지막 처리를 한다(자원반납 등)
        print('exit...')

with Hello() as h:
    h.sayHello('obama')
    h.sayHello('trump')

enter...
hello obama
hello trump
exit...


In [139]:
import torch
import torch.nn as nn
import torch.nn.functional as F
torch.manual_seed(1) # random seed 고정값
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델을 선언 및 초기화. 단순 선형 회귀이므로 input_dim=1, output_dim=1.
model = nn.Linear(1,1)
print(list(model.parameters()))
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 1800
for epoch in range(nb_epochs+1):
# H(x) 계산
  prediction = model(x_train)
# cost 계산
  cost = F.mse_loss(prediction, y_train) # 평균 제곱 오차 함수(pytorch 내장)
# cost로 H(x) 개선하는 부분
  optimizer.zero_grad() # gradient를 0으로 초기화
# 비용 함수를 미분하여 gradient 계산
  cost.backward() # backward 연산
# W와 b를 업데이트
  optimizer.step()
  if epoch % 100 == 0:
  # 100번마다 로그 출력
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()
  ))
    
# 임의의 입력 4를 선언
new_var = torch.FloatTensor([[4.0]])
# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) # forward 연산
# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된것
print("훈련 후 입력이 4일 때의 예측값 :", pred_y)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]
Epoch    0/1800 Cost: 13.103541
Epoch  100/1800 Cost: 0.002791
Epoch  200/1800 Cost: 0.001724
Epoch  300/1800 Cost: 0.001066
Epoch  400/1800 Cost: 0.000658
Epoch  500/1800 Cost: 0.000407
Epoch  600/1800 Cost: 0.000251
Epoch  700/1800 Cost: 0.000155
Epoch  800/1800 Cost: 0.000096
Epoch  900/1800 Cost: 0.000059
Epoch 1000/1800 Cost: 0.000037
Epoch 1100/1800 Cost: 0.000023
Epoch 1200/1800 Cost: 0.000014
Epoch 1300/1800 Cost: 0.000009
Epoch 1400/1800 Cost: 0.000005
Epoch 1500/1800 Cost: 0.000003
Epoch 1600/1800 Cost: 0.000002
Epoch 1700/1800 Cost: 0.000001
Epoch 1800/1800 Cost: 0.000001
훈련 후 입력이 4일 때의 예측값 : tensor([[7.9982]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[1.9990]], requires_grad=True), Parameter containing:
tensor([0.0023], requires_grad=True)]


In [140]:
import torch
import torch.nn as nn
import torch.nn.functional as F
torch.manual_seed(1)
x_train = torch.FloatTensor([[73, 80, 75],
  [93, 88, 93],
  [89, 91, 90],
  [96, 98, 100],
  [73, 66, 70]])

y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])
# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1.
model = nn.Linear(3,1)
print(list(model.parameters()))

optimizer = torch.optim.SGD(model.parameters(), lr=0.00001)
nb_epochs = 2000
for epoch in range(nb_epochs+1):
# H(x) 계산
  prediction = model(x_train) #model(x_train)은 model.forward(x_train)와 동일
  
  # cost 계산
  cost = F.mse_loss(prediction, y_train) # 평균 제곱 오차 함수(pyTorch내장)
  # cost로 H(x) 개선하는 부분
  optimizer.zero_grad() # gradient를 0으로 초기화
  cost.backward() # 비용 함수를 미분하여 gradient 계산
  optimizer.step() # W와 b를 업데이트
  if epoch % 100 == 0:
    # 100번마다 로그 출력
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))
# 임의의 입력 [73, 80, 75]를 선언
new_var = torch.FloatTensor([[73, 80, 75]])
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]
Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: 0.225990
Epoch  200/2000 Cost: 0.223910
Epoch  300/2000 Cost: 0.221936
Epoch  400/2000 Cost: 0.220061
Epoch  500/2000 Cost: 0.218269
Epoch  600/2000 Cost: 0.216570
Epoch  700/2000 Cost: 0.214958
Epoch  800/2000 Cost: 0.213411
Epoch  900/2000 Cost: 0.211951
Epoch 1000/2000 Cost: 0.210564
Epoch 1100/2000 Cost: 0.209231
Epoch 1200/2000 Cost: 0.207970
Epoch 1300/2000 Cost: 0.206765
Epoch 1400/2000 Cost: 0.205617
Epoch 1500/2000 Cost: 0.204521
Epoch 1600/2000 Cost: 0.203483
Epoch 1700/2000 Cost: 0.202489
Epoch 1800/2000 Cost: 0.201539
Epoch 1900/2000 Cost: 0.200637
Epoch 2000/2000 Cost: 0.199773
훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.2305]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires