In [ ]:
import numpy as np

tsor = np.arange(7.0) # array([0., 1., 2., 3., 4., 5., 6.])
print(tsor.ndim) #1
print(tsor.shape) # (7,)

1
<class 'tuple'>


In [ ]:
t = np.arange(1.0,13.0).reshape(4,3)
print('Rank of t:', t.ndim) # Rank of t: 2
print('Shape of t:', t.shape) # Shape of t: (4, 3)

Rank of t: 2
Shape of t: (4, 3)


In [24]:
import torch

tsor = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.,]) #torch.Tensor
torch.arange(8.0).reshape(2,4)

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [37]:
tsor.dim() # 메소드임
tsor.shape # 속성값
tsor.size() # 메소드
tsor.ndim # 속성값

print(tsor.shape, tsor.size())

torch.Size([7]) torch.Size([7])


In [39]:
t = torch.arange(1.0,13.0).reshape(4,3)
t

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [42]:
t[:,1] # tensor([ 2.,  5.,  8., 11.])
t[:,1].size() # torch.Size([4])
t[:,: -1]


tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])

In [ ]:
m1 = torch.FloatTensor([[3,3]]) # tensor([[3., 3.]])
m2 = torch.FloatTensor([[2,2]]) # tensor([[2., 2.]])

m1 + m2 # tensor([[5., 5.]])


tensor([[5., 5.]])